apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: backend-database-egress
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: hrcc-backend
  policyTypes:
    - Egress
  egress:
    - ports:
        - protocol: TCP
          port: 5432
