apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: gpu-model-download-egress
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: hrcc-gpu-inference
  policyTypes:
    - Egress
  egress:
    - ports:
        - protocol: TCP
          port: 443
