import { mkdir, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = dirname(dirname(fileURLToPath(import.meta.url)));
const outDir = join(root, "docs", "diagrams", "source");

const palette = {
  purple: ["#eee3f2", "#5d1c6a"],
  pink: ["#fce8f2", "#a93372"],
  peach: ["#ffe4d8", "#a54f2b"],
  green: ["#dff3e5", "#2f6f44"],
  teal: ["#d9f0ee", "#1d6b65"],
  amber: ["#ffe8b3", "#8a4b08"],
  blue: ["#dceafa", "#2d5f94"],
  red: ["#fde2e2", "#9b2c2c"],
  gray: ["#f1f3f5", "#495057"],
  white: ["#ffffff", "#2a0f32"],
};

function title(text, width = 880) {
  return {
    id: "title",
    type: "text",
    x: 60,
    y: 30,
    width,
    height: 38,
    text,
    fontSize: 28,
    fontFamily: "helvetica",
    strokeColor: "#2a0f32",
  };
}

function subtitle(text, y = 72, width = 1000) {
  return {
    id: `subtitle-${y}`,
    type: "text",
    x: 60,
    y,
    width,
    height: 24,
    text,
    fontSize: 16,
    fontFamily: "helvetica",
    strokeColor: "#495057",
  };
}

function node(id, x, y, width, height, text, color = "white", options = {}) {
  const [backgroundColor, strokeColor] = palette[color];
  return {
    id,
    type: options.type ?? "rectangle",
    x,
    y,
    width,
    height,
    text,
    fontSize: options.fontSize ?? 17,
    fontFamily: "helvetica",
    textAlign: "center",
    verticalAlign: "middle",
    fillStyle: "solid",
    backgroundColor,
    strokeColor,
    strokeWidth: options.strokeWidth ?? 2,
    strokeStyle: options.strokeStyle ?? "solid",
    roundness: options.type === "ellipse" ? null : { type: 3 },
  };
}

function zone(id, x, y, width, height, label, color = "gray") {
  const [backgroundColor, strokeColor] = palette[color];
  return [
    {
      id,
      type: "rectangle",
      x,
      y,
      width,
      height,
      fillStyle: "solid",
      backgroundColor,
      strokeColor,
      strokeWidth: 2,
      strokeStyle: "dashed",
      roundness: { type: 3 },
    },
    {
      id: `${id}-label`,
      type: "text",
      x: x + 18,
      y: y + 14,
      width: Math.min(width - 36, 280),
      height: 26,
      text: label,
      fontSize: 20,
      fontFamily: "helvetica",
      strokeColor,
    },
  ];
}

function arrow(id, from, to, color = "#6c757d", options = {}) {
  return {
    id,
    type: "arrow",
    x: 0,
    y: 0,
    startElementId: from,
    endElementId: to,
    strokeColor: color,
    strokeWidth: options.strokeWidth ?? 2,
    strokeStyle: options.strokeStyle ?? "solid",
    endArrowhead: "arrow",
  };
}

function note(id, x, y, width, text, color = "amber") {
  return node(id, x, y, width, 62, text, color, {
    fontSize: 15,
    strokeStyle: "dashed",
  });
}

const technical = [
  title("Technical architecture"),
  subtitle("One provider-neutral control plane; sensitive paths stay behind the application boundary."),
  ...zone("clients-zone", 45, 120, 260, 500, "Clients and intake", "blue"),
  ...zone("control-zone", 345, 120, 390, 500, "Application control plane", "purple"),
  ...zone("compute-zone", 775, 120, 330, 500, "Inference and retrieval", "amber"),
  ...zone("data-zone", 1145, 120, 300, 500, "State and evidence", "teal"),
  node("next-ui", 80, 190, 190, 72, "Next.js operator UI", "white"),
  node("mcp-client", 80, 320, 190, 72, "Local MCP clients", "white"),
  node("webhooks", 80, 450, 190, 72, "Webhook / PDF / URL intake", "white"),
  node("fastapi", 385, 180, 310, 72, "FastAPI routes + WebSocket feed", "purple"),
  node("shield", 385, 300, 145, 82, "Input shield\nPII + injection", "pink"),
  node("rbac", 550, 300, 145, 82, "RBAC\nhuman approval", "peach"),
  node("agents", 385, 440, 310, 90, "Agent fleet\nPolicy · Triage · Resume · Onboarding · Attrition", "white"),
  node("factory", 810, 180, 260, 72, "Provider-neutral LLM factory", "amber"),
  node("providers", 810, 300, 260, 92, "Injected provider\nFireworks or AMD vLLM", "white"),
  node("retrieval", 810, 460, 260, 72, "Embeddings + bounded RAG", "green"),
  node("postgres", 1180, 180, 230, 82, "Postgres + pgvector\nSQLite fallback", "teal"),
  node("audit", 1180, 320, 230, 82, "Immutable audit\ncase + approval history", "white"),
  node("metrics", 1180, 460, 230, 72, "Prometheus metrics\nhealth + GPU evidence", "gray"),
  arrow("ui-api", "next-ui", "fastapi"),
  arrow("mcp-shield", "mcp-client", "shield"),
  arrow("intake-api", "webhooks", "fastapi"),
  arrow("api-shield", "fastapi", "shield"),
  arrow("api-rbac", "fastapi", "rbac"),
  arrow("shield-agents", "shield", "agents"),
  arrow("rbac-agents", "rbac", "agents"),
  arrow("agents-factory", "agents", "factory"),
  arrow("factory-providers", "factory", "providers"),
  arrow("agents-retrieval", "agents", "retrieval"),
  arrow("retrieval-postgres", "retrieval", "postgres"),
  arrow("agents-audit", "agents", "audit"),
  arrow("providers-metrics", "providers", "metrics"),
  note("no-bypass", 790, 555, 300, "No hardcoded host or model ID.\nAll live generation routes through the factory.", "red"),
];

const productDataflow = [
  title("Product dataflow"),
  subtitle("Inputs become advisory outputs only after grounding, guardrails, and human review."),
  ...zone("inputs-zone", 45, 120, 270, 580, "Product inputs", "blue"),
  ...zone("decision-zone", 355, 120, 360, 580, "Decision-support processing", "purple"),
  ...zone("outputs-zone", 755, 120, 340, 580, "User-visible outcomes", "green"),
  ...zone("evidence-zone", 1135, 120, 280, 580, "Evidence loop", "teal"),
  node("question", 80, 180, 200, 64, "Employee policy question", "white"),
  node("ticket", 80, 285, 200, 64, "HR service ticket", "white"),
  node("resume", 80, 390, 200, 64, "Resume + job description", "white"),
  node("signals", 80, 495, 200, 64, "Employee risk signals", "white"),
  node("policy-pdf", 80, 600, 200, 64, "Versioned policy corpus", "white"),
  node("guardrails", 395, 170, 280, 72, "Sanitize · validate · blind PII", "pink"),
  node("grounding", 395, 290, 280, 72, "Retrieve · grade · cite", "purple"),
  node("decision", 395, 410, 280, 90, "Typed agent contract\nconfidence + review flag", "white"),
  node("human-gate", 395, 560, 280, 72, "Human approval for sensitive action", "peach"),
  node("policy-answer", 795, 170, 260, 72, "Cited policy answer", "green"),
  node("case-route", 795, 285, 260, 72, "Case route or urgent escalation", "amber"),
  node("resume-advice", 795, 400, 260, 72, "Blinded hiring recommendation", "blue"),
  node("retention", 795, 515, 260, 72, "Advisory retention conversation", "pink"),
  node("audit-ledger", 1170, 190, 210, 78, "Audit ledger", "white"),
  node("feedback", 1170, 330, 210, 88, "Human feedback\naccepted · edited · rejected", "white"),
  node("evals", 1170, 490, 210, 88, "Offline evals\nquality · bias · latency", "gray"),
  node("model-change", 1170, 620, 210, 64, "Controlled model release", "amber"),
  arrow("q-guard", "question", "guardrails"),
  arrow("t-guard", "ticket", "guardrails"),
  arrow("r-guard", "resume", "guardrails"),
  arrow("s-guard", "signals", "guardrails"),
  arrow("p-ground", "policy-pdf", "grounding"),
  arrow("guard-ground", "guardrails", "grounding"),
  arrow("ground-decision", "grounding", "decision"),
  arrow("decision-human", "decision", "human-gate"),
  arrow("decision-answer", "decision", "policy-answer"),
  arrow("decision-case", "decision", "case-route"),
  arrow("decision-resume", "decision", "resume-advice"),
  arrow("decision-retention", "decision", "retention"),
  arrow("out-audit", "case-route", "audit-ledger"),
  arrow("human-feedback", "retention", "feedback"),
  arrow("feedback-evals", "feedback", "evals"),
  arrow("evals-release", "evals", "model-change"),
];

const userFlow = [
  title("User flow"),
  subtitle("Role changes the surface. Open access is a demo posture, not the production authorization model."),
  node("open", 70, 160, 210, 72, "Open application", "blue"),
  node("mode", 360, 160, 250, 72, "AUTH_ENFORCE?", "amber", { type: "ellipse" }),
  node("launchpad", 690, 105, 250, 72, "Open-access launchpad", "green"),
  node("signin", 690, 225, 250, 72, "Sign in + token validation", "purple"),
  node("role", 1020, 160, 250, 72, "Resolve role", "pink", { type: "ellipse" }),
  ...zone("role-zone", 60, 340, 1310, 340, "Role-scoped workspaces", "gray"),
  node("viewer", 95, 420, 260, 92, "Viewer\nAsk policy questions\nSee citations", "green"),
  node("analyst", 410, 420, 260, 92, "Analyst\nTriage cases\nScreen resumes", "blue"),
  node("manager", 725, 420, 260, 92, "Manager\nReview attrition\nApprove workflows", "pink"),
  node("admin", 1040, 420, 260, 92, "Admin\nManage policies\nInspect audit", "purple"),
  node("review-flag", 410, 575, 260, 64, "Low confidence?", "amber", { type: "ellipse" }),
  node("human-review", 725, 575, 260, 64, "Human reviews evidence", "peach"),
  node("audit", 1040, 575, 260, 64, "Decision recorded", "teal"),
  arrow("open-mode", "open", "mode"),
  arrow("mode-launch", "mode", "launchpad", "#2f6f44"),
  arrow("mode-signin", "mode", "signin", "#5d1c6a"),
  arrow("launch-role", "launchpad", "role"),
  arrow("signin-role", "signin", "role"),
  arrow("role-viewer", "role", "viewer"),
  arrow("role-analyst", "role", "analyst"),
  arrow("role-manager", "role", "manager"),
  arrow("role-admin", "role", "admin"),
  arrow("analyst-flag", "analyst", "review-flag"),
  arrow("manager-review", "manager", "human-review"),
  arrow("flag-review", "review-flag", "human-review"),
  arrow("review-audit", "human-review", "audit"),
  note("least-privilege", 95, 575, 260, "Production rule:\nserver-side RBAC still gates actions.", "red"),
];

const agentWorkflow = [
  title("Agent workflows"),
  subtitle("Five workload shapes share contracts and audit, but keep their own failure and review rules."),
  ...zone("triage-lane", 45, 120, 1320, 105, "Ticket triage", "blue"),
  ...zone("policy-lane", 45, 245, 1320, 150, "Policy RAG loop", "purple"),
  ...zone("resume-lane", 45, 415, 1320, 105, "Resume screening", "green"),
  ...zone("onboard-lane", 45, 540, 1320, 105, "Onboarding", "amber"),
  ...zone("attrition-lane", 45, 665, 1320, 105, "Attrition + retention", "pink"),
  node("triage-in", 210, 145, 180, 56, "Ticket", "white"),
  node("triage-classify", 450, 145, 200, 56, "Typed classification", "blue"),
  node("triage-route", 710, 145, 220, 56, "Route / escalate", "amber"),
  node("triage-audit", 990, 145, 200, 56, "Case + audit", "teal"),
  node("policy-in", 210, 270, 180, 56, "Question", "white"),
  node("policy-retrieve", 450, 270, 180, 56, "Retrieve", "purple"),
  node("policy-grade", 720, 270, 180, 56, "Grade", "amber"),
  node("policy-rewrite", 720, 330, 180, 42, "Reformulate on low confidence", "peach", { fontSize: 14 }),
  node("policy-answer", 1050, 270, 180, 56, "Cite", "green"),
  node("resume-in", 210, 440, 180, 56, "JD + resume", "white"),
  node("resume-blind", 450, 440, 180, 56, "Blind PII", "pink"),
  node("resume-score", 690, 440, 180, 56, "Score skills", "green"),
  node("resume-validate", 930, 440, 180, 56, "Validate evidence", "blue"),
  node("resume-review", 1170, 440, 150, 56, "Advisory", "amber"),
  node("onboard-in", 210, 565, 180, 56, "New hire", "white"),
  node("onboard-setup", 450, 565, 180, 56, "Accounts + training", "blue"),
  node("onboard-pause", 690, 565, 180, 56, "Pause", "amber"),
  node("onboard-approve", 930, 565, 180, 56, "Human approval", "peach"),
  node("onboard-finish", 1170, 565, 150, 56, "Notify", "green"),
  node("attrition-in", 210, 690, 180, 56, "Six signals", "white"),
  node("attrition-score", 450, 690, 180, 56, "Risk model", "pink"),
  node("attrition-factor", 690, 690, 180, 56, "Top factors", "blue"),
  node("attrition-policy", 930, 690, 180, 56, "Policy grounding", "purple"),
  node("attrition-review", 1170, 690, 150, 56, "Manager", "amber"),
  arrow("t1", "triage-in", "triage-classify"),
  arrow("t2", "triage-classify", "triage-route"),
  arrow("t3", "triage-route", "triage-audit"),
  arrow("p1", "policy-in", "policy-retrieve"),
  arrow("p2", "policy-retrieve", "policy-grade"),
  arrow("p3", "policy-grade", "policy-rewrite", "#a54f2b", { strokeStyle: "dashed" }),
  arrow("p4", "policy-rewrite", "policy-retrieve", "#a54f2b", { strokeStyle: "dashed" }),
  arrow("p5", "policy-grade", "policy-answer"),
  arrow("r1", "resume-in", "resume-blind"),
  arrow("r2", "resume-blind", "resume-score"),
  arrow("r3", "resume-score", "resume-validate"),
  arrow("r4", "resume-validate", "resume-review"),
  arrow("o1", "onboard-in", "onboard-setup"),
  arrow("o2", "onboard-setup", "onboard-pause"),
  arrow("o3", "onboard-pause", "onboard-approve"),
  arrow("o4", "onboard-approve", "onboard-finish"),
  arrow("a1", "attrition-in", "attrition-score"),
  arrow("a2", "attrition-score", "attrition-factor"),
  arrow("a3", "attrition-factor", "attrition-policy"),
  arrow("a4", "attrition-policy", "attrition-review"),
];

const operations = [
  title("Operations flow"),
  subtitle("Build once for linux/amd64, prove runtime behavior, and degrade without hiding failure."),
  ...zone("delivery-zone", 45, 120, 330, 560, "Delivery", "blue"),
  ...zone("runtime-zone", 415, 120, 380, 560, "Runtime", "purple"),
  ...zone("observe-zone", 835, 120, 300, 560, "Observe and respond", "teal"),
  ...zone("improve-zone", 1175, 120, 280, 560, "Improve", "amber"),
  node("commit", 85, 180, 250, 64, "Code + tests", "white"),
  node("ci", 85, 290, 250, 72, "CI\nlint · test · static scans", "blue"),
  node("image", 85, 415, 250, 72, "linux/amd64 app images\npinned AMD ROCm/vLLM", "green"),
  node("gitops", 85, 540, 250, 72, "Compose default\nmanaged K8s optional", "purple"),
  node("config", 455, 180, 300, 72, "Injected secrets, hosts, models", "amber"),
  node("api", 455, 300, 300, 72, "FastAPI + workers", "white"),
  node("gpu", 455, 420, 300, 82, "AMD ROCm/vLLM\nor Fireworks async Batch", "peach"),
  node("fallback", 455, 555, 300, 72, "CPU + deterministic fallback", "green"),
  node("health", 875, 180, 220, 72, "Health + readiness", "teal"),
  node("metrics", 875, 300, 220, 72, "Latency · queue · errors · cost", "white"),
  node("gpu-status", 875, 420, 220, 82, "ROCm / GPU evidence\nmemory + utilization", "amber"),
  node("incident", 875, 555, 220, 72, "Runbook + rollback", "red"),
  node("evals", 1210, 180, 210, 72, "Golden evals", "blue"),
  node("benchmark", 1210, 300, 210, 72, "Measured benchmark\nor labeled simulation", "purple"),
  node("feedback", 1210, 420, 210, 72, "Human feedback", "pink"),
  node("release", 1210, 555, 210, 72, "Controlled release\nstarts next cycle", "green"),
  arrow("d1", "commit", "ci"),
  arrow("d2", "ci", "image"),
  arrow("d3", "image", "gitops"),
  arrow("d4", "gitops", "api"),
  arrow("r1", "config", "api"),
  arrow("r2", "api", "gpu"),
  arrow("r3", "api", "fallback"),
  arrow("o1", "api", "health"),
  arrow("o2", "api", "metrics"),
  arrow("o3", "gpu", "gpu-status"),
  arrow("o4", "gpu-status", "incident"),
  arrow("i1", "metrics", "evals"),
  arrow("i2", "gpu-status", "benchmark"),
  arrow("i3", "incident", "feedback"),
  arrow("i4", "evals", "release"),
  arrow("i5", "benchmark", "release"),
  arrow("i6", "feedback", "release"),
];

const platformRiskControls = [
  title("Platform risk controls"),
  subtitle("The demo uses real contracts, explicit fallbacks, and clearly labeled simulations."),
  ...zone("rocm-risk-zone", 45, 120, 400, 500, "AMD runtime setup", "peach"),
  ...zone("batch-risk-zone", 485, 120, 400, 500, "Fireworks Batch delay", "purple"),
  ...zone("k8s-risk-zone", 925, 120, 400, 500, "Deployment complexity", "blue"),
  node("rocm-risk", 95, 180, 300, 70, "Risk\nROCm and driver setup fails", "red"),
  node(
    "rocm-control",
    95,
    300,
    300,
    78,
    "Control\nPinned AMD rocm/vllm gfx94X image",
    "green"
  ),
  node(
    "rocm-evidence",
    95,
    430,
    300,
    82,
    "Evidence\nlinux/amd64 · /dev/kfd · /dev/dri · health",
    "white",
    { fontSize: 15 }
  ),
  note("rocm-note", 95, 550, 300, "Host AMD kernel driver is still required.", "amber"),
  node("batch-risk", 535, 180, 300, 70, "Risk\nBatch capacity is delayed", "red"),
  node("batch-control", 535, 290, 300, 68, "Control\nVisible asynchronous state", "green"),
  node("batch-pending", 535, 395, 300, 72, "PENDING\nqueued; interactive work continues", "amber"),
  node(
    "batch-evidence",
    535,
    515,
    300,
    72,
    "Evidence\n10s polling · check after 30 min",
    "white"
  ),
  node("k8s-risk", 975, 180, 300, 70, "Risk\nKubernetes obscures the demo", "red"),
  node("compose-control", 975, 290, 300, 68, "Default demo\nDocker Compose", "green"),
  node("managed-option", 975, 395, 300, 72, "Optional production template\nmanaged EKS / GKE", "blue"),
  node(
    "scale-evidence",
    975,
    515,
    300,
    72,
    "Scaling projection\nSIMULATED = true",
    "amber"
  ),
  arrow("rocm-a", "rocm-risk", "rocm-control"),
  arrow("rocm-b", "rocm-control", "rocm-evidence"),
  arrow("batch-a", "batch-risk", "batch-control"),
  arrow("batch-b", "batch-control", "batch-pending"),
  arrow("batch-c", "batch-pending", "batch-evidence"),
  arrow("k8s-a", "k8s-risk", "compose-control"),
  arrow("k8s-b", "compose-control", "managed-option", "#2d5f94", { strokeStyle: "dashed" }),
  arrow("k8s-c", "managed-option", "scale-evidence", "#8a4b08", { strokeStyle: "dashed" }),
  note(
    "claim-boundary",
    340,
    660,
    690,
    "Claim boundary: manifests and projections show engineering readiness; only named-hardware runtime logs prove AMD utilization.",
    "teal"
  ),
];

const diagrams = {
  "technical-architecture": technical,
  "product-dataflow": productDataflow,
  "user-flow": userFlow,
  "agent-workflows": agentWorkflow,
  "operations-flow": operations,
  "platform-risk-controls": platformRiskControls,
};

await mkdir(outDir, { recursive: true });
for (const [name, elements] of Object.entries(diagrams)) {
  await writeFile(join(outDir, `${name}.elements.json`), `${JSON.stringify(elements, null, 2)}\n`);
}

console.log(`Generated ${Object.keys(diagrams).length} diagram sources in ${outDir}`);
